//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Authentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile_image
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string image_address { get; set; }
    
        public virtual user user { get; set; }
    }
}
